### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 108adams** [inversify/inversify-chrome-devtools#4]
Hi. I try to use your extension :)

It does not work, as in fact unfinished

I can help with development, but I need some help with that.

If you find it worth your effort, just let me know, I'll do a PR with my updates/propositions, I still haven't got it working as supposed, but at least I've got a DevTools Panel with the tool rendered. I cannot just connect the panel with the inversify instance in the web app.

Yours
Adam

**Comment by remojansen** [comment]
Hi @108adams thanks for showing interest on this. I haven't work on the dev tools in a long time due to lack of time. I plan to get back to it as soon as I can. I would love some help but right now the code is quite incomplete which makes it quite hard for someone to contribute. Do you have experience with chrome apps? I'm closing this issue because all issues are reported at the main repo. You can follow up on this using the following issue https://github.com/inversify/InversifyJS/issues/215
